hyperparameters : 
  CatBoostRegressor:
    iterations: [100, 200, 300]
    learning_rate: [0.01, 0.05, 0.1]
    depth: [6, 8, 10]
    l2_leaf_reg: [1, 3, 5, 7]
    random_seed: [42]
    verbose: [False]
  XGBRegressor:
    n_estimators: [100, 200, 300]
    max_depth: [3, 6, 9]
    learning_rate: [0.01, 0.05, 0.1]
    # subsample: [0.7, 0.8, 0.9]
    # colsample_bytree: [0.7, 0.8, 0.9]
    gamma: [0, 0.1, 0.2]
    random_state: [42]