# conf/base/parameters.yml
target_column: "price"
to_feature_store: True
test_fraction: 0.3
random_state: 42
run_name: "full_project"
use_feature_selection: False
feature_selection: "tree_based"  # Options: "rfe", "tree_based"
model_name: "wine"
baseline_model_params:
  # Common parameters that work for both CatBoost and XGBoost
  n_estimators: 100
  learning_rate: 0.1
  max_depth: 6
  random_state: 42
  # Model-specific parameters will be handled in model initialization
drop_col_options:
  - designation
  - province
  - region_1
  - region_2
  - taster_name
  - taster_twitter_handle
  - title
  - winery
# columns_to_fill:
#   - country
#   - region_1
#   - taster_name
#   - province
# na_values_col_drop:
#   - variety
na_columns_to_unknown:
  - "country"
  - "province"
  - "region_1"
  - "region_2"
  - "variety"
split_data_and_validate:
  target_column: "price"
  test_fraction: 0.2
  random_state: 42